### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mcmikemn** [thingsiplay/fpath#1]
This might be user error, but when I run fpath (e.g., `fpath` or `ls | fpath`) , I get:
```
File "/usr/local/bin/fpath", line 1148
help=f"Subjects: {", ".join(choices)}",
                   ^
SyntaxError: f-string: expecting '}'
```

I'm using Ubutnu 22.04.4.

**Comment by thingsiplay** [comment]
Hi thank you for the report. This might be an oversight be me, but oddly enough it works fine on my Python (again I have a newer version than Ubuntu 22.04). Would you please edit the `fpath` file with an editor this line to replace 2 double quotation marks to single? If this works, then I will update the code. Go to line 1148 in fpath:

```python
        help=f"Subjects: {", ".join(choices)}",
```

change it to 

```python
        help=f"Subjects: {', '.join(choices)}",
```

However, as with the other script, this might be a case of incompatibility with older Python version.

**Comment by mcmikemn** [comment]
Changing double quotes to single quotes on line 1148 fixed the issue for me. Thanks again!

**Comment by thingsiplay** [comment]
Good to know. I have no idea why this works for me, as it is not valid Python code. I will update the script quickly with this fix. Thank you for the report and testing.

Edit: https://github.com/thingsiplay/fpath/commit/457794bc6c981faf4544cb0ab59850b864abfb5e
